### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by brobinson3** [brobinson3/Testing_Thresholds#1]
Hi everyone! Thanks in advance for participating in this code review. Here is the type of feedback I'm looking for:

1. Is the README file clear? Are there parts I should add/drop?
2. Are the files organized in a logical way? Can organization be improved?
3. If you were going to try to run the code (you don't need to), do you think the instructions and code look clear enough to do so?
4. Because this code is finished, I don't need feedback on the code itself, but if you want to look through it (out of curiosity or something) and you find errors or have questions, please bring them up!

Thank you!

**Comment by jdherman** [comment]
Thanks Beth. I didn't try running it, but here are some things to consider:

- Downloading the data could be streamlined. At some point you had a shell script or command-line way of doing this? You could add it to the repo, or explain in the readme. Then users could automate the download.

- Somewhere in the readme you might want to explain that in the paper, this code was run over many combinations of `time` (window size) and `agreement` parameters. A user would not be able to recreate the figures without doing all of these combinations.

- The multiple-source historical data folder doesn't have much context (I realize it's not critical to the experiment). But you can briefly say where it's from and what it's being used for.

- The organization is clear. Some of the naming could be more direct. For example you don't need to call things `_Final`, it's already implied. The folder for figure scripts could just be called `figures`. etc.

- Last thing, at the top of the readme where you have the citation, you could include a one-sentence summary of what the code is meant to do. The example I wrote on the group website was `A statistical testing approach for threshold-based classifiers of vulnerable scenarios in long-term streamflow projections.`, something like that.

These are very general things, hopefully others have specific code-level questions and comments. Thanks again for volunteering for the first week!

**Comment by jscohen4** [comment]
![image](https://user-images.githubusercontent.com/30808540/51214979-59309400-18d4-11e9-94f5-b67c2bca7254.png)

**Comment by njmolla** [comment]
Hi Beth, 
Most of my comments are on the main script since I think the others covered the repository organization well.
•	The README was easy to understand, and I think I could figure out how to run the code based on it (I didn’t try it out, though).
•	Not super important, but it would make it easier for users if rather than having to check or change locations of files in the script, it was written as a function for which the necessary paths were an input.
•	The code is well organized, the different sections of the code are clear and the overall purpose of the different sections is clear. It’s great how many comments you have.
•	Not sure if this is on purpose, but you import pandas as pd and as star, which makes it hard to tell which libraries are actually being used and whether there are pandas functions being used that won’t have the prefix.
•	I understand the unit conversion functions at the beginning, but the calculation would be much easier to follow if it were ordered more like how a human would interpret it or if parentheses were added. Also not a big deal but easy to way to make it easier to check and change.
•	Unclear variable names, like dff, cmip_annQ_spag (maybe this is because I don’t have the context).
•	The if statements in the error calculations section can be turned into nested ifs. This would make the logic a little easier to follow and have less repeated code.

**Comment by mrlmautner** [comment]
1. I didn't run the code, but it seems pretty straightforward and the code is well commented and clear.
2. It wasn't clear to me what the Multiple_Source... folder serves as, but other than that the organization is pretty straight forward. I think it helps that you link to the paper which has the methodology
3. Yes
4. A few things:
- In the figures scripts, I might add a quick comment at the top of each script to describe what the figure contains. Maybe even just a paraphrasing of the figure caption for each.
- I'm not sure what the copywrite implications are, but I have seen in other GitHub pages they post a figure or two from the article with the description which looks kinda nice
- It might be a little late, but you reuse a couple of functions in almost all of your scripts and it might make sense to nest those in a separate script and just load that at the top of each of the scripts, for conciseness
- The "Remaking Figures" is not detailed enough to be included, so either scrap it, or add a little more detail.
